[[plugins]]
package = "@netlify/plugin-lighthouse"

# optional, deploy the lighthouse report to a path under your site
[plugins.inputs.audits]
output_path = "reports/lighthouse.html"


[[plugins]]
package = "netlify-plugin-checklinks"

[plugins.inputs]
entryPoints = ["*.html"]
skipPatterns = ["guitartab.html"]
pretty = true
checkExternal = true
