name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the staging branch
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  family_tree_images:
    name: Check Family Tree Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test images
        run: python3 ./tests/family_tree_images.py

  broken_links:
    name: Check Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Check Broken Links
        uses: technote-space/broken-link-checker-action@v2

  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: oven-sh/setup-bun@v2
      - name: Prettier check
        run: bun x prettier . --check
