name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the staging branch
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  family_tree_images:
    name: Check Family Tree Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Test images
        run: uv run python ./tests/family_tree_images.py

  broken_links:
    name: Check Broken Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee
          restore-keys: cache-lychee

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: '-v --root-dir "$(pwd)" --accept ''200..=204, 401, 999'' --cache --max-cache-age 1d .'

  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - uses: oven-sh/setup-bun@v2
      - name: Prettier check
        run: bunx prettier . --check
